



































}  );    />      }}        target.src = '/fallback-image.jpg';        const target = e.target as HTMLImageElement;      onError={(e) => {      loading="lazy"      className={className}      height={height}      width={width}      alt={alt}      src={url}    <Image  return (  }    return <Skeleton variant="rectangular" width={width} height={height} />;  if (!url) {  const { url, error } = useImageLoader(src);export default function CachedImage({ src, alt, width, height, className }: CachedImageProps) {}  className?: string;  height: number;  width: number;  alt: string;  src: string;interface CachedImageProps {import { Skeleton } from '@mui/material';import { useImageLoader } from '@/hooks/useImageLoader';import Image from 'next/image';'use client';